"""empty message

Revision ID: b80394bf8d9c
Revises: bb73519e5a4f
Create Date: 2023-10-04 23:20:53.050473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80394bf8d9c'
down_revision: Union[str, None] = 'bb73519e5a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'balance')
    op.add_column('statistic', sa.Column('native_balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statistic', 'native_balance')
    op.add_column('addresses', sa.Column('balance', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
